version: "3.9"
services:
  postgres:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: hird
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./infra/db/init:/docker-entrypoint-initdb.d
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports: ["9000:9000", "9001:9001"]
    volumes:
      - minio:/data
  api:
    build: ./services/api
    depends_on: [postgres, minio]
    environment:
      SPRING_PROFILES_ACTIVE: local
    ports: ["8080:8080"]
  ui:
    build: ./services/ui
    depends_on: [api]
    ports: ["5173:5173"]
volumes:
  pgdata:
  minio:
