version: "3.9"


services:
postgres:
image: postgres:16-alpine
container_name: hird-postgres
restart: unless-stopped
environment:
POSTGRES_DB: ${POSTGRES_DB:-hird}
POSTGRES_USER: ${POSTGRES_USER:-hird}
POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-hirdpw}
ports:
- "${POSTGRES_PORT:-5432}:5432"
volumes:
- pgdata:/var/lib/postgresql/data
- ./db/init:/docker-entrypoint-initdb.d # place init SQL here
healthcheck:
test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
interval: 5s
timeout: 3s
retries: 20


pgadmin:
image: dpage/pgadmin4:8.12
container_name: hird-pgadmin
restart: unless-stopped
depends_on:
postgres:
condition: service_healthy
environment:
PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@local}
PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-adminpw}
ports:
- "${PGADMIN_PORT:-8081}:80"
volumes:
- pgadmin:/var/lib/pgadmin


volumes:
pgdata:
pgadmin: