from fastapi import APIRouter, Response
from io import BytesIO
from reportlab.pdfgen import canvas

router = APIRouter(prefix="/report", tags=["report"])


@router.get("/{city}.pdf")
def get_report(city: str):
    buffer = BytesIO()
    c = canvas.Canvas(buffer)
    c.setFont("Helvetica", 14)
    c.drawString(100, 750, f"Housing Insights Report for {city}")
    c.drawString(100, 720, "This is a stub PDF generated by FastAPI.")
    c.showPage()
    c.save()

    buffer.seek(0)
    return Response(content=buffer.read(), media_type="application/pdf")
