version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on: # Tells application service to wait until postgres container is up and running
      - postgres
    networks:
      - api-network
    env_file:
      - .env

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: housing_db
    ports:
      - "5433:5432"
    networks:
      - api-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

networks:
  api-network:
    driver: bridge
# Default network driver, that creates
# a private internal network on my host machine
# containers attached to the same network
# can communicate with each other

volumes:
  # Define named volume for PostgreSQL data persistence
  # This creates a Docker-managed volume that persists data
  # even when the container is removed, ensuring database
  # data survives container restarts and updates
  postgres_data:
